#!/usr/bin/env bash

CODE_CACHE=${HOME}/.cloud_profiler

#
# distro OS platform information API
# https://pypi.org/project/distro/#files
#
DISTRO_DIR=distro-1.3.0
DISTRO_TAR=${DISTRO_DIR}.tar.gz
DISTRO_LINK="https://files.pythonhosted.org/packages/d2/42/3b059929a920cd9d4e91e7a5e35f0d2ed75211f8f4e877be9d1bde9fdf46/${DISTRO_TAR}"
DISTRO=${CODE_CACHE}/distro.py
