name: CI

on:
  push:
    branches:
      - main

env:
  CP_REPO: https://github.com/shinhyungyang/cloud_profiler
  SQUASH_REPO: https://github.com/shinhyungyang/squash
  GITROOT: ${HOME}/git 
  BUILDROOT: ${HOME}/build

jobs:
  build-test-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-24.04]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: build cloud_profiler ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: install dependencies
        run: |
          sudo apt -q update
          sudo apt -q -y install git cmake swig g++ \
            openjdk-21-jdk cppzmq-dev libpapi-dev libboost-all-dev
          mkdir ${HOME}/git ${HOME}/build
      - name: build squash
        run: |
          cd ${HOME}/git
          git clone ${SQUASH_REPO} --branch alpine --recursive --depth 1
          mkdir ${HOME}/build/build_release-squash
          cd ${HOME}/build/build_release-squash
          cmake ${HOME}/git/squash && make -j$(nproc)
          sudo make install
      - name: build cloud_profiler
        run: |
          cd ${HOME}/git
          git clone ${CP_REPO}
          mkdir ${HOME}/build/build_release-cloud_profiler
          cd ${HOME}/build/build_release-cloud_profiler
          cmake ${HOME}/git/cloud_profiler && make -j$(nproc)
          sudo make install
      - name: clean up
        run: |
          rm -rf ${HOME}/git ${HOME}/build
